package oracle.summit.selfservice.model.views.readonly;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 23 13:53:05 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CardTypesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CardTypesVOImpl() {
    }
}

